//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daramkun.DaramRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daramkun.DaramRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   모든 파일(*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업이 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyComplete {
            get {
                return ResourceManager.GetString("ApplyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지금까지 작업한 파일 이름 변경을 실제 파일에 적용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyWorked {
            get {
                return ResourceManager.GetString("ApplyWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 내용을 적용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AskApplyWorked {
            get {
                return ResourceManager.GetString("AskApplyWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트를 확인할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotCheckUpdate {
            get {
                return ResourceManager.GetString("CannotCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다람 리네이머과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DaramRenamer {
            get {
                return ResourceManager.GetString("DaramRenamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorRaised {
            get {
                return ResourceManager.GetString("ErrorRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 디렉토리가 없습니다. 그대로 진행하시려면 &apos;예&apos;를 눌러주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JustContinueWhenNoExistPath {
            get {
                return ResourceManager.GetString("JustContinueWhenNoExistPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아니오(&amp;N)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 디렉토리가 실제로 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoExistDirectory {
            get {
                return ResourceManager.GetString("NoExistDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 버전에 대한 업데이트가 있습니다. 홈페이지에서 다운로드해주세요.
        ///하단 버튼을 통해 홈페이지로 바로 가실 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoticeUpdate {
            get {
                return ResourceManager.GetString("NoticeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인(&amp;O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; 경로에 파일이 이미 있거나 원본 파일을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathError_IOException {
            get {
                return ResourceManager.GetString("PathError_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; 파일의 경로를 변경할 권한이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathError_NoAuthentication {
            get {
                return ResourceManager.GetString("PathError_NoAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;의 디렉토리가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathError_NoPath {
            get {
                return ResourceManager.GetString("PathError_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; 파일의 경로가 너무 깁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathError_PathIsTooLong {
            get {
                return ResourceManager.GetString("PathError_PathIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알 수 없는 이유로 파일의 경로를 변경할 수 없었습니다: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathError_Unknown {
            get {
                return ResourceManager.GetString("PathError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알 수 없는 오류가 발생했습니다. error.log를 참고해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseCheckLog {
            get {
                return ResourceManager.GetString("PleaseCheckLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows XP 이하의 운영체제는 더 이상 지원하지 않습니다.
        ///XP 사용자의 경우 1.x 버전을 사용해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseUseLegacy {
            get {
                return ResourceManager.GetString("PleaseUseLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}/{1}개의 파일에 대해 이름을 변경하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThatFilesNameChanged {
            get {
                return ResourceManager.GetString("ThatFilesNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThereIsUpdate {
            get {
                return ResourceManager.GetString("ThereIsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 프로그램의 버전은 현재 최신버전입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThisIsStable {
            get {
                return ResourceManager.GetString("ThisIsStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈페이지로(&amp;H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToHomepage {
            get {
                return ResourceManager.GetString("ToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예(&amp;Y)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
