//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daramkun.DaramRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daramkun.DaramRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   모든 파일(*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업이 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplyComplete {
            get {
                return ResourceManager.GetString("ApplyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지금까지 작업한 파일 이름 변경을 실제 파일에 적용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplyWorked {
            get {
                return ResourceManager.GetString("ApplyWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 내용을 적용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AskApplyWorked {
            get {
                return ResourceManager.GetString("AskApplyWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일이 경로에 없는 경우 자동으로 리스트에서 제거.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Autoremove {
            get {
                return ResourceManager.GetString("Autoremove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일괄 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatchTab_BatchProcess {
            get {
                return ResourceManager.GetString("BatchTab_BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트를 확인할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CannotCheckUpdate {
            get {
                return ResourceManager.GetString("CannotCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원래 경로와 수정할 경로가 다른 경우 이동하지 않고 파일 복사.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyWhenTransaction {
            get {
                return ResourceManager.GetString("CopyWhenTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다람 리네이머과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DaramRenamer {
            get {
                return ResourceManager.GetString("DaramRenamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성한 날짜 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DateTab_AddCreation {
            get {
                return ResourceManager.GetString("DateTab_AddCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막 접근 날짜 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DateTab_AddLastAccess {
            get {
                return ResourceManager.GetString("DateTab_AddLastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막 수정 날짜 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DateTab_AddLastWrite {
            get {
                return ResourceManager.GetString("DateTab_AddLastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorRaised {
            get {
                return ResourceManager.GetString("ErrorRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExtTab_AddExt {
            get {
                return ResourceManager.GetString("ExtTab_AddExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExtTab_DeleteExt {
            get {
                return ResourceManager.GetString("ExtTab_DeleteExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExtTab_ReplaceExt {
            get {
                return ResourceManager.GetString("ExtTab_ReplaceExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 대소문자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExtTab_UpperLower {
            get {
                return ResourceManager.GetString("ExtTab_UpperLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가능한 경우 하드웨어 가속 렌더링 사용.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HardwareRenderingSupport {
            get {
                return ResourceManager.GetString("HardwareRenderingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가할 확장자:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_AddExt {
            get {
                return ResourceManager.GetString("InTab_AddExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 묶인 문자열에 대해 실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_AllEnclosed {
            get {
                return ResourceManager.GetString("InTab_AllEnclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾아보기...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_Browse {
            get {
                return ResourceManager.GetString("InTab_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 확장자:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ChangeExt {
            get {
                return ResourceManager.GetString("InTab_ChangeExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   붙일 문자열:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ConcatString {
            get {
                return ResourceManager.GetString("InTab_ConcatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_DelAll {
            get {
                return ResourceManager.GetString("InTab_DelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자리수:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_DigitCount {
            get {
                return ResourceManager.GetString("InTab_DigitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   뒤 문자열:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_EnclosedPost {
            get {
                return ResourceManager.GetString("InTab_EnclosedPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앞 문자열:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_EnclosedPre {
            get {
                return ResourceManager.GetString("InTab_EnclosedPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형식:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_Format {
            get {
                return ResourceManager.GetString("InTab_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형식 문자열:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_FormatString {
            get {
                return ResourceManager.GetString("InTab_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   증감할 값:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_IncDecValue {
            get {
                return ResourceManager.GetString("InTab_IncDecValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 포함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_IncludeExt {
            get {
                return ResourceManager.GetString("InTab_IncludeExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간격:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_Interval {
            get {
                return ResourceManager.GetString("InTab_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원본 문자열:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_OriginalString {
            get {
                return ResourceManager.GetString("InTab_OriginalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꿀 경로:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_Path {
            get {
                return ResourceManager.GetString("InTab_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_Position {
            get {
                return ResourceManager.GetString("InTab_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리 방법:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ProcessMethod {
            get {
                return ResourceManager.GetString("InTab_ProcessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규 표현식:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_Regexp {
            get {
                return ResourceManager.GetString("InTab_Regexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자로만 된 단어만 남김과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_RemoveAllWordWithoutNum {
            get {
                return ResourceManager.GetString("InTab_RemoveAllWordWithoutNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 숫자 남김과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_RemoveWithoutAllNum {
            get {
                return ResourceManager.GetString("InTab_RemoveWithoutAllNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꿀 문자열:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ReplaceString {
            get {
                return ResourceManager.GetString("InTab_ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소문자로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ToLower {
            get {
                return ResourceManager.GetString("InTab_ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맨 뒤과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ToPost {
            get {
                return ResourceManager.GetString("InTab_ToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맨 앞과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ToPre {
            get {
                return ResourceManager.GetString("InTab_ToPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대문자로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ToUpper {
            get {
                return ResourceManager.GetString("InTab_ToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단어 맨 앞만 대문자로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_ToUpperOneLetter {
            get {
                return ResourceManager.GetString("InTab_ToUpperOneLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 빈 칸 제거 포함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTab_TrimWithExt {
            get {
                return ResourceManager.GetString("InTab_TrimWithExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 디렉토리가 없습니다. 그대로 진행하시려면 &apos;예&apos;를 눌러주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string JustContinueWhenNoExistPath {
            get {
                return ResourceManager.GetString("JustContinueWhenNoExistPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이선스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListView_ChangedName {
            get {
                return ResourceManager.GetString("ListView_ChangedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치할 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListView_ChangedPath {
            get {
                return ResourceManager.GetString("ListView_ChangedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원본 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListView_OriginalName {
            get {
                return ResourceManager.GetString("ListView_OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치한 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListView_OriginalPath {
            get {
                return ResourceManager.GetString("ListView_OriginalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일괄 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_BatchProcess {
            get {
                return ResourceManager.GetString("MainTab_BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_DateProcess {
            get {
                return ResourceManager.GetString("MainTab_DateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_ExtensionProcess {
            get {
                return ResourceManager.GetString("MainTab_ExtensionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_NumberProcess {
            get {
                return ResourceManager.GetString("MainTab_NumberProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_PathProcess {
            get {
                return ResourceManager.GetString("MainTab_PathProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규표현식과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_RegexpProcess {
            get {
                return ResourceManager.GetString("MainTab_RegexpProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_Settings {
            get {
                return ResourceManager.GetString("MainTab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTab_StringProcess {
            get {
                return ResourceManager.GetString("MainTab_StringProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아니오(&amp;N)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 디렉토리가 실제로 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoExistDirectory {
            get {
                return ResourceManager.GetString("NoExistDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 버전에 대한 업데이트가 있습니다. 홈페이지에서 다운로드해주세요.
        ///하단 버튼을 통해 홈페이지로 바로 가실 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoticeUpdate {
            get {
                return ResourceManager.GetString("NoticeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번호 붙이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NumTab_AddNum {
            get {
                return ResourceManager.GetString("NumTab_AddNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자만 남기고 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NumTab_DelWithoutNum {
            get {
                return ResourceManager.GetString("NumTab_DelWithoutNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자 증감과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NumTab_IncreaseDecrease {
            get {
                return ResourceManager.GetString("NumTab_IncreaseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자 자리수 맞추기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NumTab_SameDigits {
            get {
                return ResourceManager.GetString("NumTab_SameDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인(&amp;O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; 경로에 파일이 이미 있거나 원본 파일을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PathError_IOException {
            get {
                return ResourceManager.GetString("PathError_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; 파일의 경로를 변경할 권한이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PathError_NoAuthentication {
            get {
                return ResourceManager.GetString("PathError_NoAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;의 디렉토리가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PathError_NoPath {
            get {
                return ResourceManager.GetString("PathError_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; 파일의 경로가 너무 깁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PathError_PathIsTooLong {
            get {
                return ResourceManager.GetString("PathError_PathIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알 수 없는 이유로 파일의 경로를 변경할 수 없었습니다: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PathError_Unknown {
            get {
                return ResourceManager.GetString("PathError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PathTab_ChangePath {
            get {
                return ResourceManager.GetString("PathTab_ChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알 수 없는 오류가 발생했습니다. error.log를 참고해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseCheckLog {
            get {
                return ResourceManager.GetString("PleaseCheckLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows XP 이하의 운영체제는 더 이상 지원하지 않습니다.
        ///XP 사용자의 경우 1.x 버전을 사용해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseUseLegacy {
            get {
                return ResourceManager.GetString("PleaseUseLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규표현식과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegexpTab_RegularExpression {
            get {
                return ResourceManager.GetString("RegexpTab_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열 붙이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringTab_Concat {
            get {
                return ResourceManager.GetString("StringTab_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   묶인 문자열 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringTab_DeleteEnclosed {
            get {
                return ResourceManager.GetString("StringTab_DeleteEnclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringTab_DeleteName {
            get {
                return ResourceManager.GetString("StringTab_DeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열 바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringTab_Replace {
            get {
                return ResourceManager.GetString("StringTab_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   양 옆 빈 칸 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringTab_Trim {
            get {
                return ResourceManager.GetString("StringTab_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 대소문자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringTab_UpperLower {
            get {
                return ResourceManager.GetString("StringTab_UpperLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}/{1}개의 파일에 대해 이름을 변경하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThatFilesNameChanged {
            get {
                return ResourceManager.GetString("ThatFilesNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThereIsUpdate {
            get {
                return ResourceManager.GetString("ThereIsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 기능은 준비 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThisFeatureIsNotReady {
            get {
                return ResourceManager.GetString("ThisFeatureIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 프로그램의 버전은 현재 최신버전입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThisIsStable {
            get {
                return ResourceManager.GetString("ThisIsStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈페이지로(&amp;H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToHomepage {
            get {
                return ResourceManager.GetString("ToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트를 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_CheckUpdate {
            get {
                return ResourceManager.GetString("ToolBar_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   목록을 삭제합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_ClearList {
            get {
                return ResourceManager.GetString("ToolBar_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PayPal을 통해 기부합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Donation {
            get {
                return ResourceManager.GetString("ToolBar_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   버그 또는 건의 요청에 대해 피드백합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Feedback {
            get {
                return ResourceManager.GetString("ToolBar_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 항목을 보다 아래로 내립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_ItemToDown {
            get {
                return ResourceManager.GetString("ToolBar_ItemToDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 항목을 보다 위로 올립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_ItemToUp {
            get {
                return ResourceManager.GetString("ToolBar_ItemToUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름을 일괄 변환할 파일을 불러옵니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_LoadFile {
            get {
                return ResourceManager.GetString("ToolBar_LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행 취소를 되돌립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Redo {
            get {
                return ResourceManager.GetString("ToolBar_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경을 취소합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Rollback {
            get {
                return ResourceManager.GetString("ToolBar_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항목을 이름순으로 오름차순 정렬합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Sort {
            get {
                return ResourceManager.GetString("ToolBar_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름을 일괄 변경합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Transaction {
            get {
                return ResourceManager.GetString("ToolBar_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이전 실행을 취소합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBar_Undo {
            get {
                return ResourceManager.GetString("ToolBar_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예(&amp;Y)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
