//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daramkun.DaramRenamer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HardwareTurnOn {
            get {
                return ((bool)(this["HardwareTurnOn"]));
            }
            set {
                this["HardwareTurnOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRemoveTurnOn {
            get {
                return ((bool)(this["AutoRemoveTurnOn"]));
            }
            set {
                this["AutoRemoveTurnOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"XFsoLiopXF0oLiopIC0gKFswLTldKikoLiopXCgoKFtBLVpdfFthLXpdKSopIChbMC05XSopeChbMC05XSopICgoW0EtWl18W2Etel18WzAtOV0pKikgKChbQS1aXXxbYS16XXxbMC05XSkqKVwpLigoWzAtOV18W2Etel0pKik=;KC4qKSAtIChbMC05XSopLigoWzAtOV18W2Etel0pKik=;KFtBLVpdKikoWzAtOV0qKS4oKFswLTldfFthLXpdKSop;KFtBLVpdKilfKFswLTldKikuKChbMC05XXxbYS16XSkqKQ==")]
        public string RegexpOriginal {
            get {
                return ((string)(this["RegexpOriginal"]));
            }
            set {
                this["RegexpOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3sxfV0gezJ9IC0gezN9ICh7NH0gezV9eHs2fSB7N30gezh9KS57OX0=;ezF9IC0gezJ9LnszfQ==;ezF" +
            "9ezJ9LnszfQ==;ezF9X3syfS57M30=")]
        public string RegexpFormat {
            get {
                return ((string)(this["RegexpFormat"]));
            }
            set {
                this["RegexpFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileCopyWhenApply {
            get {
                return ((bool)(this["FileCopyWhenApply"]));
            }
            set {
                this["FileCopyWhenApply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilenameAutoFix {
            get {
                return ((bool)(this["FilenameAutoFix"]));
            }
            set {
                this["FilenameAutoFix"] = value;
            }
        }
    }
}
