<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DaramRenamer</RootNamespace>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Assets\Strings.csv" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="TagLibSharp" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DaramRenamer.CodeGen\DaramRenamer.CodeGen.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <Import Project="..\Modules\FileTypeDetector\Daramee.FileTypeDetector.Shared\Daramee.FileTypeDetector.Shared.projitems" Label="Shared" />

</Project>
