using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DaramRenamer.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class RegistryGenerator : IIncrementalGenerator
{
    private const string CommandDefinition = "DaramRenamer.Registry.CommandDefinitionAttribute";
    private const string ConditionDefinition = "DaramRenamer.Registry.ConditionDefinitionAttribute";
    private const string OptionDefinition = "DaramRenamer.Registry.OptionDefinitionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;
        context.RegisterSourceOutput(compilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        var commands = GetDefinitions(compilation, CommandDefinition).ToArray();
        var conditions = GetDefinitions(compilation, ConditionDefinition).ToArray();
        var options = GetOptions(compilation).GroupBy(option => option.OwnerMetadataName)
            .ToDictionary(group => group.Key, group => group.ToArray());

        if (commands.Length == 0 && conditions.Length == 0)
            return;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using DaramRenamer.Commands;");
        source.AppendLine("using DaramRenamer.Conditions;");
        source.AppendLine();
        source.AppendLine("namespace DaramRenamer.Registry;");
        source.AppendLine();
        source.AppendLine("public static partial class DaramRenamerRegistry");
        source.AppendLine("{");
        source.AppendLine("    public static IReadOnlyList<CommandDescriptor> Commands { get; } =");
        source.AppendLine("    [");
        for (var i = 0; i < commands.Length; ++i)
        {
            AppendCommand(source, commands[i], options);
            source.AppendLine(i == commands.Length - 1 ? string.Empty : ",");
        }
        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    public static IReadOnlyList<ConditionDescriptor> Conditions { get; } =");
        source.AppendLine("    [");
        for (var i = 0; i < conditions.Length; ++i)
        {
            AppendCondition(source, conditions[i], options);
            source.AppendLine(i == conditions.Length - 1 ? string.Empty : ",");
        }
        source.AppendLine("    ];");
        source.AppendLine("}");

        context.AddSource("DaramRenamerRegistry.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AppendCommand(StringBuilder source, Definition definition,
        IReadOnlyDictionary<string, Option[]> options)
    {
        var typeName = definition.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        source.AppendLine($"        Command<{typeName}>(");
        source.AppendLine($"            \"{Escape(definition.Id)}\",");
        source.AppendLine($"            \"{Escape(definition.LocalizationKey)}\",");
        source.AppendLine($"            new {typeName}().Category,");
        source.AppendLine($"            new {typeName}().Order,");
        AppendOptions(source, definition, options);
        AppendLegacyIds(source, definition);
        source.Append("        )");
    }

    private static void AppendCondition(StringBuilder source, Definition definition,
        IReadOnlyDictionary<string, Option[]> options)
    {
        var typeName = definition.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        source.AppendLine($"        Condition<{typeName}>(");
        source.AppendLine($"            \"{Escape(definition.Id)}\",");
        source.AppendLine($"            \"{Escape(definition.LocalizationKey)}\",");
        source.AppendLine($"            new {typeName}().Order,");
        AppendOptions(source, definition, options);
        AppendLegacyIds(source, definition);
        source.Append("        )");
    }

    private static void AppendOptions(StringBuilder source, Definition definition,
        IReadOnlyDictionary<string, Option[]> options)
    {
        source.AppendLine("            [");
        if (options.TryGetValue(GetMetadataNameWithNamespace(definition.Type), out var ownerOptions))
        {
            for (var i = 0; i < ownerOptions.Length; ++i)
            {
                var option = ownerOptions[i];
                var ownerType = definition.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var optionType = option.Property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append($"                Option<{ownerType}, {optionType}>(\"{Escape(option.PropertyName)}\", \"{Escape(option.LocalizationKey)}\", {GetValueKind(option.Property.Type)}, static x => x.{option.PropertyName}, static (x, v) => x.{option.PropertyName} = v)");
                source.AppendLine(i == ownerOptions.Length - 1 ? string.Empty : ",");
            }
        }
        source.Append("            ]");
    }

    private static void AppendLegacyIds(StringBuilder source, Definition definition)
    {
        foreach (var legacyId in definition.LegacyIds)
            source.Append($", \"{Escape(legacyId)}\"");
        source.AppendLine();
    }

    private static string GetValueKind(ITypeSymbol type)
    {
        var nullable = type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
        var effective = nullable && type is INamedTypeSymbol namedType ? namedType.TypeArguments[0] : type;

        if (effective.SpecialType == SpecialType.System_String)
            return "OptionValueKind.String";
        if (effective.SpecialType == SpecialType.System_Boolean)
            return nullable ? "OptionValueKind.NullableBoolean" : "OptionValueKind.Boolean";
        if (effective.SpecialType == SpecialType.System_Int32)
            return nullable ? "OptionValueKind.NullableInt32" : "OptionValueKind.Int32";
        if (effective.SpecialType == SpecialType.System_UInt32)
            return nullable ? "OptionValueKind.NullableUInt32" : "OptionValueKind.UInt32";
        if (effective.TypeKind == TypeKind.Enum)
            return "OptionValueKind.Enum";

        return "OptionValueKind.String";
    }

    private static IEnumerable<Definition> GetDefinitions(Compilation compilation, string attributeName)
    {
        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != attributeName)
                continue;

            if (attribute.ConstructorArguments.Length < 3)
                continue;

            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                continue;

            var id = attribute.ConstructorArguments[1].Value as string ?? string.Empty;
            var localizationKey = attribute.ConstructorArguments[2].Value as string ?? string.Empty;
            var legacyIds = attribute.ConstructorArguments.Length >= 4
                ? attribute.ConstructorArguments[3].Values
                    .Select(value => value.Value as string)
                    .Where(value => value != null)
                    .Cast<string>()
                    .ToArray()
                : Array.Empty<string>();

            yield return new Definition(type, id, localizationKey, legacyIds);
        }
    }

    private static IEnumerable<Option> GetOptions(Compilation compilation)
    {
        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != OptionDefinition)
                continue;

            if (attribute.ConstructorArguments.Length < 3)
                continue;

            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol ownerType)
                continue;

            var propertyName = attribute.ConstructorArguments[1].Value as string ?? string.Empty;
            var localizationKey = attribute.ConstructorArguments[2].Value as string ?? string.Empty;
            var property = ownerType.GetMembers(propertyName).OfType<IPropertySymbol>().FirstOrDefault();
            if (property == null)
                continue;

            yield return new Option(GetMetadataNameWithNamespace(ownerType), propertyName, localizationKey, property);
        }
    }

    private static string GetMetadataNameWithNamespace(INamedTypeSymbol type) =>
        type.ContainingNamespace.IsGlobalNamespace
            ? type.MetadataName
            : $"{type.ContainingNamespace.ToDisplayString()}.{type.MetadataName}";

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class Definition
    {
        public Definition(INamedTypeSymbol type, string id, string localizationKey, string[] legacyIds)
        {
            Type = type;
            Id = id;
            LocalizationKey = localizationKey;
            LegacyIds = legacyIds;
        }

        public INamedTypeSymbol Type { get; }
        public string Id { get; }
        public string LocalizationKey { get; }
        public string[] LegacyIds { get; }
    }

    private sealed class Option
    {
        public Option(string ownerMetadataName, string propertyName, string localizationKey, IPropertySymbol property)
        {
            OwnerMetadataName = ownerMetadataName;
            PropertyName = propertyName;
            LocalizationKey = localizationKey;
            Property = property;
        }

        public string OwnerMetadataName { get; }
        public string PropertyName { get; }
        public string LocalizationKey { get; }
        public IPropertySymbol Property { get; }
    }
}
